#!/usr/bin/env python3
# ABOUTME: Generate the 36 Goal 1 matrix specs: 3 variants x 12 datasets, N=1 trial each.
# ABOUTME: Outputs examples/specs/goal1/<variant>/<dataset>.yaml + .frozen.yaml + provenance.yaml.

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

import yaml

from razorback_plugin_dab.datasets import DAB_DATASETS
from razorback_plugin_dab.generate.workspace_readme import WORKSPACE_VARIANTS


REPO_ROOT = Path(__file__).resolve().parents[2]
DATA_ROOT = "/Users/clkao/git/dataagentbench/data"


def build_spec(variant: str, dataset: str) -> dict:
    experiment = f"goal1-{variant}-{dataset.lower()}"
    return {
        "version": 1,
        "experiment": experiment,
        "agent": {
            "kind": "claude-cli",
            "model": "claude-opus-4-7",
            "sampling": {"temperature": 0.0},
            "tools_allowed": ["Bash", "Read", "Write", "Edit", "Glob", "Grep"],
        },
        "benchmark": {
            "kind": "harbor_dab",
            "data_root": DATA_ROOT,
            "datasets": [dataset],
            "workspace_variant": variant,
            "hints": True,
        },
        "trials": 1,
        "experiment_meta": {
            "max_budget_usd": 20.0,
            "estimated_cost_usd": 2.0,
        },
        "observers": [
            {"kind": "jsonl", "path": "events.jsonl"},
            {"kind": "stdout"},
        ],
    }


def emit_spec(out_dir: Path, variant: str, dataset: str) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    spec_path = out_dir / f"{dataset}.yaml"
    spec = build_spec(variant, dataset)
    header = (
        f"# ABOUTME: Goal 1 matrix cell — variant={variant}, dataset={dataset}, N=1.\n"
        "# ABOUTME: Generated by examples/drivers/generate-dab-paper-matrix-specs.py.\n"
    )
    spec_path.write_text(header + yaml.safe_dump(spec, sort_keys=False))
    return spec_path


def freeze_spec(spec_path: Path) -> None:
    subprocess.run(
        ["uv", "run", "rk", "freeze", str(spec_path), "--allow-missing"],
        cwd=REPO_ROOT,
        check=True,
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--out-root",
        default=str(REPO_ROOT / "examples" / "specs" / "goal1"),
        help="Root directory under which <variant>/<dataset>.yaml lands.",
    )
    parser.add_argument(
        "--freeze",
        action="store_true",
        help="Run rk freeze on each emitted spec immediately.",
    )
    args = parser.parse_args()

    out_root = Path(args.out_root)
    emitted: list[Path] = []
    for variant in WORKSPACE_VARIANTS:
        for ds in DAB_DATASETS:
            spec_path = emit_spec(out_root / variant, variant, ds.name)
            emitted.append(spec_path)
            print(f"wrote {spec_path.relative_to(REPO_ROOT)}")

    if args.freeze:
        for spec_path in emitted:
            print(f"freezing {spec_path.relative_to(REPO_ROOT)}")
            freeze_spec(spec_path)

    expected = len(WORKSPACE_VARIANTS) * len(DAB_DATASETS)
    print(
        f"emitted {len(emitted)} specs "
        f"({len(WORKSPACE_VARIANTS)} variants x {len(DAB_DATASETS)} datasets); "
        f"expected {expected}."
    )
    if len(emitted) != expected:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
