#!/usr/bin/env python3
# ABOUTME: Generate the Goal 1 matrix specs: workspace_variants x datasets, N=1 trial each.
# ABOUTME: Reads inventory from the DAB Harbor-style dataset definition (AC-3).

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

import yaml

from razorback_plugin_dab.dataset_def import load_default_definition


REPO_ROOT = Path(__file__).resolve().parents[2]

SOLVER_WORKFLOW_PATH = "./examples/solver_workflows/dab_paper_matrix"


def _build_agent_block(variant: str) -> dict:
    """PKG-26: spacedock variant → spacedock_solver (halt/resume + skill injection);
    direct-minimal + direct-structured → claude-cli (now a ClaudeCode subclass).
    """
    if variant == "spacedock":
        return {
            "kind": "spacedock_solver",
            "runtime": "claude",
            "model": "claude-opus-4-7",
            "sampling": {"temperature": 0.0, "top_p": None, "seed": None},
            "solver_workflow": SOLVER_WORKFLOW_PATH,
            "max_turns": 200,
            "tools_allowed": ["Bash", "Read", "Write", "Edit", "Glob", "Grep"],
            "tools_denied": [],
        }
    return {
        "kind": "claude-cli",
        "model": "claude-opus-4-7",
        "sampling": {"temperature": 0.0},
        "tools_allowed": ["Bash", "Read", "Write", "Edit", "Glob", "Grep"],
    }


def build_spec(variant: str, dataset: str, dataset_ref: str) -> dict:
    experiment = f"goal1-{variant}-{dataset.lower()}"
    return {
        "version": 1,
        "experiment": experiment,
        "agent": _build_agent_block(variant),
        "benchmark": {
            "kind": "harbor_dab",
            "dataset": dataset_ref,
            "datasets": [dataset],
            "workspace_variant": variant,
            "hints": True,
            "query_mode": "batch",
        },
        "trials": 1,
        "experiment_meta": {
            "max_budget_usd": 20.0,
            "estimated_cost_usd": 2.0,
        },
        "observers": [
            {"kind": "jsonl", "path": "events.jsonl"},
            {"kind": "stdout"},
        ],
    }


def emit_spec(out_dir: Path, variant: str, dataset: str, dataset_ref: str) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    spec_path = out_dir / f"{dataset}.yaml"
    spec = build_spec(variant, dataset, dataset_ref)
    header = (
        f"# ABOUTME: Goal 1 matrix cell — variant={variant}, dataset={dataset}, N=1.\n"
        "# ABOUTME: Generated by examples/drivers/generate-dab-paper-matrix-specs.py.\n"
    )
    spec_path.write_text(header + yaml.safe_dump(spec, sort_keys=False))
    return spec_path


def freeze_spec(spec_path: Path) -> None:
    subprocess.run(
        ["uv", "run", "rk", "freeze", str(spec_path), "--allow-missing"],
        cwd=REPO_ROOT,
        check=True,
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--out-root",
        default=str(REPO_ROOT / "examples" / "specs" / "goal1"),
        help="Root directory under which <variant>/<dataset>.yaml lands.",
    )
    parser.add_argument(
        "--freeze",
        action="store_true",
        help="Run rk freeze on each emitted spec immediately.",
    )
    args = parser.parse_args()

    definition = load_default_definition()
    out_root = Path(args.out_root)
    emitted: list[Path] = []
    for variant in definition.workspace_variants:
        for ds_entry in definition.datasets:
            spec_path = emit_spec(out_root / variant, variant, ds_entry.name, definition.ref)
            emitted.append(spec_path)
            print(f"wrote {spec_path.relative_to(REPO_ROOT)}")

    if args.freeze:
        for spec_path in emitted:
            print(f"freezing {spec_path.relative_to(REPO_ROOT)}")
            freeze_spec(spec_path)

    expected = len(definition.workspace_variants) * len(definition.datasets)
    print(
        f"emitted {len(emitted)} specs "
        f"({len(definition.workspace_variants)} variants x {len(definition.datasets)} datasets); "
        f"expected {expected}."
    )
    if len(emitted) != expected:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
